# Generated by Django 5.2.13 on 2026-07-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariobiblioteca',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
