# Generated by Django 5.2.13 on 2026-07-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuariobiblioteca_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariobiblioteca',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuariobiblioteca',
            name='nombre',
        ),
    ]
