# Generated by Django 5.2.13 on 2026-07-08 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='El numero esta mal checalo')])),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('direccion', models.TextField(blank=True)),
                ('favorito', models.BooleanField(default=False)),
            ],
        ),
    ]
